author: Ferran Muiños
email: ferran.muinos@irbbarcelona.org
description: "mat course"
twitter_username: fmuinos
github_username: koszulordie
show_excerpts: true
future: true
# Build settings
theme: jekyll-theme-cayman
# theme: Minima
show_downloads: "true"
permalink: /mat/:title
